name: Build and Deploy
on: 
  push: 
    branches: 
      - main

jobs: 
  build_and_deploy: 
    runs-on: ubuntu-latest
    env: 
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
    steps: 
    - uses: actions/checkout@v5
    - name: Set up Node
      uses: actions/setup-node@v4
      with: 
        node-version: '23'
    - run: npm install -g wrangler
    - run: npm ci
    - run: npm run build  
    - run: wrangler deploy